basePath: /
definitions:
  battlefield.AddShipsRequest:
    properties:
      coords:
        type: string
    type: object
  battlefield.CreateFieldRequest:
    properties:
      range:
        type: integer
    type: object
  battlefield.HTTPError:
    properties:
      err:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: garatuev@gmail.com
    name: Shamil Garatuev
  description: This is a battleships game server.
  license: {}
  title: Swagger Example API
  version: "2.0"
paths:
  /clear:
    post:
      consumes:
      - application/json
      description: clear the battlefield
      responses:
        "200": {}
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: clear the battlefield
      tags:
      - BattleField
  /create-matrix:
    post:
      consumes:
      - application/json
      description: create new battlefield with provided size
      parameters:
      - description: createParams
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/battlefield.CreateFieldRequest'
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/battlefield.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/battlefield.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: create new battlefield
      tags:
      - BattleField
  /ship:
    post:
      consumes:
      - application/json
      description: |-
        add ships to battlefield
        input params should be like this:
        "A1 B2,C4 C6,E7 F8" where first coordinate is one corner of ship, second - other.
        ships can be square or rectangular
        ships can't be placed on top of each other and near each other.
      parameters:
      - description: coordinates
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/battlefield.AddShipsRequest'
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/battlefield.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/battlefield.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: add ships to battlefield
      tags:
      - Ships
swagger: "2.0"
